spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    open-in-view: true
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.1.87:3307/hibernate?serverTimezone=Asia/Shanghai&autoReconnect=true&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: 123456

